### ISSUE TITLE
UI Unresponsive

### ISSUE THREAD

**Issue by davemast** [NewPointe/Earthquake-Detector#1]
The top right portion of the UI does not respond to earthquakes, even in extreme cases. See photos for issue reproduction. 
![7DD4F58E-3E7B-4FF3-83DB-4A59C0811974](https://user-images.githubusercontent.com/3999018/97449580-34ba7600-1908-11eb-8e2f-6bb93ee40217.png)
![C296908D-DC86-4C94-9484-88A85055F9A3](https://user-images.githubusercontent.com/3999018/97449621-40a63800-1908-11eb-8c25-d791565eea61.jpeg)
![51651A45-869D-43EE-93DF-9AD48A52F069](https://user-images.githubusercontent.com/3999018/97449626-413ece80-1908-11eb-9f8f-41f5f0a4afd6.jpeg)

**Comment by LukeLevesque** [comment]
Looks like the quality of the sensors isn't up to spec. We'll get those replaced for the next version.
